### ISSUE TITLE
publier les données comme un package R

### ISSUE THREAD

**Issue by romainfrancois** [ptiflus/CartePrenoms#1]
est-ce que vous prévoyez de publier les données dans un package R. 
Le package `babynames` de Hadley est très populaire, mais une version française serait interessante.

**Comment by FlorianGD** [comment]
Je ne me suis pas posé la question. En effet, je ne sais pas faire (mais je n'ai pas cherché). Les données sont en license ouverte, je dois donc avoir le droit de les redistribuer via un package.
Avez-vous un lien expliquant la démarche pour publier un package ?

**Comment by romainfrancois** [comment]
Je peux m'en occuper un de ces soirs, probablement ici (https://github.com/ThinkRstat/prenoms) 
je te rajouterai bien sur en tant qu'auteur du pkg etc ...

**Comment by FlorianGD** [comment]
Ok !
